### ISSUE TITLE
Why are you using nearest neighbors? 

### ISSUE THREAD

**Issue by akshath123** [mr-ravin/CNN-Autoencoders#1]
Hello Ravin! I was looking at your code but didn't understand the decoder part of the network why are you using nearest neighbors instead we can you transpose convolution to resizing the image? I have seen this implemented in other autoencoder scripts too, so why are we doing this and if there is research article regarding the use of nearest neighbors in autoencoders please provide me the link. Thank you!

Regards,
Akshath Varugeese

**Comment by mr-ravin** [comment]
Hello akshath,  We are using nearest neighbour for the purpose of upsampling. In the decoder phase, if we use transpose convolution, then while upsampling the data (as we move forward in decoder) the quality of data get degraded. Already the input from encoder have less dimension due to downsampling with pooling layers, and if we use transpose convolution during upsampling in  decoder phase. The quality of upsampled data  become degraded (i.e. pooling layer) leading to generation of low quality data in inference phase. So, to get better upsampled data, we use nearest neighbours to upsample the data and then pass this upsampled data to a convolution layer, and repeat this process for all convolution layers present in the decoder of Autoencoders. 
Hope it helped to clear your doubt :)
Regards,
Ravin Kumar

**Comment by akshath123** [comment]
Yes, it clears my doubt thank you!
